version: 3

tasks:
  run: |
    docker run \
    --volume=/var/lib/drone:/data \
    --env=DRONE_GITLAB_SERVER=https://gitlab.com \
    --env=DRONE_GITLAB_CLIENT_ID=05136e57d80189bef462 \
    --env=DRONE_GITLAB_CLIENT_SECRET=7c229228a77d2cbddaa61ddc78d45e \
    --env=DRONE_RPC_SECRET=super-duper-secret \
    --env=DRONE_SERVER_HOST=drone.company.com \
    --env=DRONE_SERVER_PROTO=https \
    --publish=80:80 \
    --publish=443:443 \
    --restart=always \
    --detach=true \
    --name=drone \
    drone/drone:2